language: go

go:
  - 1.5
  - tip

sudo: false

before_install:
  - export GO15VENDOREXPERIMENT=1

install:
  - echo 'nop'

script:
  - go test -v $(go list ./... | grep -v /vendor/)

addons:
  apt:
    packages:
      - rpm

notifications:
  email: false
